
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: lambda-probot-express

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:

  probot:
    handler: handler.probot

    environment:
      WEBHOOK_SECRET: development
      APP_ID: 2312

    events:
      - http:
         path: /probot
         method: get

      - http:
         path: /probot
         method: post
